name: Arnaud Geiser
description: >
    Arnaud Geiser - Random thoughts
markdown: kramdown
highlighter: rouge
destination: docs
url: https://arnaudgeiser.ch

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 10
